package com.ghost.zeku.domain.model.enum

enum class MediaSourceMaterial {
    ORIGINAL, MANGA, LIGHT_NOVEL, VISUAL_NOVEL, VIDEO_GAME, OTHER, NOVEL, DOUJINSHI, ANIME, WEB_NOVEL, LIVE_ACTION, GAME, MULTIMEDIA_PROJECT, PICTURE_BOOK, UNKNOWN
}